# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         AI-Pathfinding-AStar
version:      0.10
version_from: lib/AI/Pathfinding/AStar.pm
installdirs:  site
requires:
    Heap::Binomial:                0
    Heap::Elem:                    0
    Test::More:                    0.11

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
